### PR TITLE
fix(combobox): the whole input should trigger the dropdown

### LINKED ISSUE #410: Combobox doesn't open when twistie is clicked
This can be reproduced here

https://angular.carbondesignsystem.com/?selectedKind=Combobox&selectedStory=Basic&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

1. Click in center of combo and the dropdown appears
2. Issue: Click the twistie and the dropdown fails to appear

### PR DESCRIPTION
**Pull request by cal-smith**
closes #410

### CODE REVIEW

File: src/combobox/combobox.component.ts [hunk 1]
```diff
@@ -248,7 +248,7 @@ export class ComboBox implements OnChanges, OnInit, AfterViewInit, AfterContentI
 						this.selectedValue = "";
 						this.propagateChangeCallback(null);
 					}
-					// not gaurding these since the nativeElement has to be loaded
+					// not guarding these since the nativeElement has to be loaded
```
Comment (zvonimirfras) [inline src/combobox/combobox.component.ts]: 🙌

File: src/combobox/combobox.component.ts [hunk 2]
```diff
@@ -286,12 +286,15 @@ export class ComboBox implements OnChanges, OnInit, AfterViewInit, AfterContentI
 	hostkeys(ev: KeyboardEvent) {
 		if (ev.key === "Escape") {
 			this.closeDropdown();
-		} else if (ev.key === "ArrowDown" && !this.dropdownMenu.nativeElement.contains(ev.target)) {
+		} else if (ev.key === "ArrowDown"
```
Comment (zvonimirfras) [inline src/combobox/combobox.component.ts]: This might be a good time to add IE11 specific key values
```suggestion
		} else if ((ev.key === "ArrowDown" || ev.key === "Down") // `"Down"` is IE specific value
```

File: src/combobox/combobox.component.ts [hunk 3]
```diff
@@ -286,12 +286,15 @@ export class ComboBox implements OnChanges, OnInit, AfterViewInit, AfterContentI
...
+			&& (!this.dropdownMenu || !this.dropdownMenu.nativeElement.contains(ev.target))) {
 			ev.stopPropagation();
 			this.openDropdown();
 			setTimeout(() => this.view.getCurrentElement().focus(), 0);
-		} else if (ev.key === "ArrowUp" && this.dropdownMenu.nativeElement.contains(ev.target) && !this.view["hasPrevElement"]()) {
-			this.elementRef.nativeElement.querySelector(".combobox_input").focus();
+		} else if (ev.key === "ArrowUp"
```
Comment (zvonimirfras) [inline src/combobox/combobox.component.ts]:
```suggestion
		} else if ((ev.key === "ArrowUp" || ev.key === "Up") // `"Up"` is IE specific value
```

File: src/combobox/combobox.component.ts (hunk 1 above)
Comment (cal-smith) [reply src/combobox/combobox.component.ts]: Haha, every PR I've been trying to fix any typos I see

File: src/combobox/combobox.component.ts (hunk 2 above)
Comment (cal-smith) [reply src/combobox/combobox.component.ts]: 🙌 absolutely

File: src/combobox/combobox.component.ts (hunk 3 above)
Comment (cal-smith) [reply src/combobox/combobox.component.ts]: ✨
