### PR TITLE
fix(datepicker): Make flatpickrOptions an input

### LINKED ISSUE #575: `flatpickrOptions` and `flatpickrOptionsRange` should be inputs
This will allow devs to easily provide custom ones for, i.e. disabling dates.

### PR DESCRIPTION
**Pull request by youda97**
closes #575

### CODE REVIEW

File: src/datepicker/datepicker.component.ts [hunk 1]
```diff
@@ -120,20 +120,38 @@ export class DatePicker implements OnDestroy {
...
+	get flatpickrOptions(): FlatpickrOptions {
+		const plugins = [...this.plugins];
+		if (this.range) {
+			plugins.push(rangePlugin({ input: "#" + this.id + "-rangeInput"}));
+		}
+		return Object.assign({}, this._flatpickrOptions, this.flatpickrBaseOptions, {plugins});
+	}
+
+	@Input()
+	set flatpickrOptionsRange (options: FlatpickrOptions) {
```
Comment (zvonimirfras) [inline src/datepicker/datepicker.component.ts]: Didn't we talk about deprecating range and just using `flatpickrOptions` with `range` controlling the switch between the versions?

Everything else seems correct except `flatpickrOptionsRange` became an input except getting deprecated.

Comment (cal-smith) [reply src/datepicker/datepicker.component.ts]: lol yeah that shouldn't be an `Input` ... the rest of the implementation is valid I think though
