### PR TITLE
fix(dialog): fix dialog in IE11

### LINKED ISSUE #159: Overflow menu positioning in IE 11
Hi 

I am using overflow menu, it cannot work correctly in IE11, and when I run storybook(https://angular.carbondesignsystem.com) in IE11, I see a blank page. Does carbon-components-angular support IE?

### PR DESCRIPTION
**Pull request by cal-smith**
closes #159

### CODE REVIEW

File: .storybook/addons.js [hunk 1]
```diff
@@ -1,3 +1,21 @@
+import "core-js/es6/symbol";
```
Comment (asudoh) [inline .storybook/addons.js]: Weighing in a bit - Carbon vanilla/React variants maintain separate lists of "polyfills modules" so consumers know what polyfill they need to run the library on IE11. Great to have a similar thing, if the topic has not been documented.

File: src/dialog/dialog.component.ts [hunk 2]
```diff
@@ -137,7 +137,11 @@ export class Dialog implements OnInit, AfterViewInit, OnDestroy {
 	 */
 	ngAfterViewInit() {
 		const dialogElement = this.dialog.nativeElement;
-		dialogElement.classList = `${dialogElement.classList} ${this.dialogConfig.wrapperClass}`;
+		if (this.dialogConfig.wrapperClass) {
```
Comment (zvonimirfras) [inline src/dialog/dialog.component.ts]: Maybe add a comment to blame IE11 for the complication?

File: src/dialog/dialog.directive.ts [hunk 3]
```diff
@@ -61,7 +61,7 @@ export class DialogDirective implements OnInit, OnDestroy, OnChanges {
 	 * @type {string}
 	 * @memberof DialogDirective
 	 */
-	@Input() wrapperClass: string;
+	@Input() wrapperClass = "";
```
Comment (zvonimirfras) [inline src/dialog/dialog.directive.ts]: It can't be undefined or empty string signifies something?

File: .storybook/addons.js [hunk 4]
```diff
@@ -1,3 +1,21 @@
...
+import "core-js/es6/array";
+import "core-js/es6/regexp";
+import "core-js/es6/map";
+import "core-js/es6/set";
+import "core-js/es6/reflect";
+
+import "core-js/es7/reflect";
+import "zone.js/dist/zone";
+
 import '@storybook/addon-actions/register';
```
Comment (zvonimirfras) [inline .storybook/addons.js]: Single quotes 👀

File: .storybook/addons.js (hunk 1 above)
Comment (cal-smith) [reply .storybook/addons.js]: I'll have to double check what Angular CLI ships/recommends ... this should mirror that, or at least we should be following what they recommend.

It's probably a good idea to review our actual polyfill dependency list though, the less we have to rely on the better.

File: src/dialog/dialog.directive.ts (hunk 3 above)
Comment (cal-smith) [reply src/dialog/dialog.directive.ts]: It could probably go back to undefined ... I tend to prefer initializing to useful (non undefined) values where possible though.

File: .storybook/addons.js (hunk 4 above)
Comment (cal-smith) [reply .storybook/addons.js]: that's what happens when the linter doesn't lint all the things 😂

File: src/dialog/dialog.directive.ts (hunk 3 above)
Comment (zvonimirfras) [reply src/dialog/dialog.directive.ts]: That implies that a value is needed when it's not.

Comment (cal-smith) [reply src/dialog/dialog.directive.ts]: Not really? It just implies that it's set to an empty string

File: src/dialog/dialog.component.ts (hunk 2 above)
Comment (zvonimirfras) [reply src/dialog/dialog.component.ts]: Is github not showing the comment or you think it's no longer necessary?

Comment (cal-smith) [reply src/dialog/dialog.component.ts]: I actually totally forgot to add a comment 😅

File: src/dialog/dialog.component.ts [hunk 5]
```diff
@@ -137,7 +137,14 @@ export class Dialog implements OnInit, AfterViewInit, OnDestroy {
 	 */
 	ngAfterViewInit() {
 		const dialogElement = this.dialog.nativeElement;
-		dialogElement.classList = `${dialogElement.classList} ${this.dialogConfig.wrapperClass}`;
+		// split the wrapper class list and apply seperatly to avoid IE from
+		// 1. throwing an error due to asigning a readonly property (classList)
```
Comment (zvonimirfras) [inline src/dialog/dialog.component.ts]:
```suggestion
		// 1. throwing an error due to assigning a readonly property (classList)
```

File: src/dialog/dialog.component.ts [hunk 6]
```diff
@@ -137,7 +137,14 @@ export class Dialog implements OnInit, AfterViewInit, OnDestroy {
 	 */
 	ngAfterViewInit() {
 		const dialogElement = this.dialog.nativeElement;
-		dialogElement.classList = `${dialogElement.classList} ${this.dialogConfig.wrapperClass}`;
+		// split the wrapper class list and apply seperatly to avoid IE from
```
Comment (zvonimirfras) [inline src/dialog/dialog.component.ts]:
```suggestion
		// split the wrapper class list and apply separately to avoid IE from
```

File: src/dialog/dialog.component.ts [hunk 7]
```diff
@@ -137,7 +137,14 @@ export class Dialog implements OnInit, AfterViewInit, OnDestroy {
...
+		// 1. throwing an error due to asigning a readonly property (classList)
+		// 2. throwing an SyntaxError due to passing an empty string to .add
```
Comment (zvonimirfras) [inline src/dialog/dialog.component.ts]:
```suggestion
		// 2. throwing a SyntaxError due to passing an empty string to `add`
```

File: src/dialog/tooltip/tooltip.stories.ts [hunk 8]
```diff
@@ -35,10 +35,12 @@ storiesOf("Tooltip", module)
 			</ng-template>
 			<span
 				[ibmTooltip]="template"
+				appendToBody="true"
```
Comment (zvonimirfras) [inline src/dialog/tooltip/tooltip.stories.ts]: No longer needed 🎉 
```suggestion
```

File: src/dialog/tooltip/tooltip.stories.ts [hunk 9]
```diff
@@ -35,10 +35,12 @@ storiesOf("Tooltip", module)
...
 				trigger="click"
 				placement="bottom"
 				style="cursor: pointer;">
 				Click for tooltip
 			</span>
+			<ibm-dialog-placeholder></ibm-dialog-placeholder>
```
Comment (zvonimirfras) [inline src/dialog/tooltip/tooltip.stories.ts]: Deprecated 🙌 
```suggestion
			<ibm-placeholder></ibm-placeholder>
```
