### PR TITLE
fix(date picker): stop click propagation when calendar is clicked

### LINKED ISSUE #876: DatePicker is closing parent tooltip/dialog.
When I use a DatePicker inside a tooltip or dialog if I click any of the buttons to switch the month or the year it closes the calendar and the containing tooltip/dialog.

DatePickerDefect1

## Steps to reproduce the issue

[Codesandbox](https://codesandbox.io/s/carbon-components-angular-pwqzh)

1. Click on the 'Trigger' to open the tooltip
2. Click the '>' to move to the next month

The tooltip closes.

## Additional information

Or you can also try this download from CodeSandbox [carbon-components-angular-simple-reproduce.zip](https://github.com/IBM/carbon-components-angular/files/3784969/carbon-components-angular-simple-reproduce.zip)

### PR DESCRIPTION
**Pull request by Donisius**
Closes #876 

Clicking on the flatpickr calendar causes the click event to propagate. It now stops the click propagation.

### CODE REVIEW

File: src/datepicker/datepicker.component.ts [hunk 1]
```diff
@@ -271,7 +271,7 @@ export class DatePicker implements OnDestroy, OnChanges, AfterViewChecked {
 	 */
 	protected updateClassNames() {
 		if (!this.elementRef) { return; }
-
+		document.querySelector(".flatpickr-calendar").addEventListener("click", (event) => { event.stopPropagation(); });
```
Comment (youda97) [inline src/datepicker/datepicker.component.ts]: Probably want to add the `.open` class to your query selector in case there are two date pickers

Comment (Donisius) [reply src/datepicker/datepicker.component.ts]: good point!

File: src/datepicker/datepicker.component.ts [hunk 2]
```diff
@@ -271,14 +271,17 @@ export class DatePicker implements OnDestroy, OnChanges, AfterViewChecked {
...
 		// get all the possible flatpickrs in the document - we need to add classes to (potentially) all of them
 		const calendarContainer = document.querySelectorAll(".flatpickr-calendar");
 		const monthContainer = document.querySelectorAll(".flatpickr-month");
 		const weekdaysContainer = document.querySelectorAll(".flatpickr-weekdays");
 		const weekdayContainer = document.querySelectorAll(".flatpickr-weekday");
 		const daysContainer = document.querySelectorAll(".flatpickr-days");
 		const dayContainer = document.querySelectorAll(".flatpickr-day");
+		const openCalendarContainer = document.querySelectorAll(".flatpickr-calendar.open");
+
+		Array.from(openCalendarContainer)
```
Comment (cal-smith) [inline src/datepicker/datepicker.component.ts]: I'm not sure we need to query for only `.open` calendars ... also there may be value in removing the event listener before adding it (since we may end up adding quite a few listeners over the lifetime of the component).

File: src/datepicker/datepicker.component.ts [hunk 3]
```diff
@@ -280,6 +279,12 @@ export class DatePicker implements OnDestroy, OnChanges, AfterViewChecked {
 		const daysContainer = document.querySelectorAll(".flatpickr-days");
 		const dayContainer = document.querySelectorAll(".flatpickr-day");
 
+		Array.from(calendarContainer)
+			.forEach(calendar => {
+				calendar.removeEventListener("click", event => event.stopPropagation());
+				calendar.addEventListener("click", event => event.stopPropagation());
```
Comment (cal-smith) [inline src/datepicker/datepicker.component.ts]: In order to remove it you'll have to add the listener as a property - something like `protected preventCalendarClose = event => event.stopPropagation();` and then pass that to add/remove listener

File: src/datepicker/datepicker.component.ts [hunk 4]
```diff
@@ -284,6 +283,12 @@ export class DatePicker implements OnDestroy, OnChanges, AfterViewChecked {
 		const daysContainer = document.querySelectorAll(".flatpickr-days");
 		const dayContainer = document.querySelectorAll(".flatpickr-day");
 
+		Array.from(calendarContainer)
```
Comment (zvonimirfras) [inline src/datepicker/datepicker.component.ts]: This doesn't belong to `updateClassNames`. It's not doing anything to class names and it's not necessary to update any class names.
Either function needs a better name or this needs to be moved out to a different function and used in a different way. Since it's a protected function and not used anywhere else, former might make more sense.

Comment (Donisius) [reply src/datepicker/datepicker.component.ts]: That makes sense
