### PR TITLE
fix(notification): add aria label and description

### LINKED ISSUE #3144: [Accesibility]: Notifications are missing label and description fields
Image

### PR DESCRIPTION
**Pull request by r1shabhsharma**
closes: https://github.com/carbon-design-system/carbon-components-angular/issues/3144

Added `aria-label` and `aria-describedby` to notification element

Screenshot 2025-05-20 at 6 27 59 PM

### CODE REVIEW

File: src/notification/actionable-notification.component.ts [hunk 1]
```diff
@@ -83,6 +83,8 @@ export class ActionableNotification extends BaseNotification {
 	}
 
 	@HostBinding("attr.id") notificationID = `notification-${ActionableNotification.notificationCount++}`;
+	@HostBinding("attr.aria-label") notificationLabel = `Notification`;
+	@HostBinding("attr.aria-describedby") notificationDescription = `${this.notificationObj.type} notification`;
```
Comment (Akshat55) [inline src/notification/actionable-notification.component.ts:87]: `aria-describedby` attribute usually references an ID not text.

**Review by Akshat55 — CHANGES_REQUESTED** [review]

File: src/notification/actionable-notification.component.ts (hunk 1 above)
Comment (r1shabhsharma) [reply src/notification/actionable-notification.component.ts]: Changed it to the text `Notification-ID`

File: src/notification/actionable-notification.component.ts [hunk 2]
```diff
@@ -82,7 +82,9 @@ export class ActionableNotification extends BaseNotification {
 		this._notificationObj = Object.assign({}, this.defaultNotificationObj, obj);
 	}
 
-	@HostBinding("attr.id") notificationID = `notification-${ActionableNotification.notificationCount++}`;
+	@HostBinding("attr.id") notificationID = `notification-${ActionableNotification.notificationCount}`;
+	@HostBinding("attr.aria-label") notificationLabel = `Notification`;
+	@HostBinding("attr.aria-describedby") notificationDescription = `Notification-${ActionableNotification.notificationCount++}`;
```
Comment (Akshat55) [inline src/notification/actionable-notification.component.ts:87]:
```suggestion
	notificationID = `notification-${ActionableNotification.notificationCount++}`;
	@HostBinding("attr.aria-labelledby") labelledby= `Notification-${this.notificationID}`; // May need to use a getter, double check.
```

Update the code to use `aria-labelledBy`, you can remove `aria-label`. The ID should be assigned to the following element (title):

```
<div *ngIf="!notificationObj.template" cdsActionableTitle [innerHTML]="notificationObj.title"></div>
```

**Review by Akshat55 — CHANGES_REQUESTED** [review]

**Review by Akshat55 — CHANGES_REQUESTED** [review]

File: src/notification/actionable-notification.component.ts [hunk 3]
```diff
@@ -82,7 +82,9 @@ export class ActionableNotification extends BaseNotification {
 		this._notificationObj = Object.assign({}, this.defaultNotificationObj, obj);
 	}
 
-	@HostBinding("attr.id") notificationID = `notification-${ActionableNotification.notificationCount++}`;
+	@HostBinding("attr.id") notificationID = `notification-${ActionableNotification.notificationCount}`;
+	@HostBinding("attr.aria-labelledBy") notificationLabel = `Notification`;
+	@HostBinding("attr.aria-describedby") notificationDescription = `Notification-${ActionableNotification.notificationCount++}`;
```
[the remark this answers is not in the document]
Comment (r1shabhsharma) [reply src/notification/actionable-notification.component.ts]: Addressed

**Review by Akshat55 — APPROVED** [review]
