### PR TITLE
fix(deploy): deploy versioned documentation

### LINKED ISSUE #199: Versioned Documentation

### PR DESCRIPTION
**Pull request by cal-smith**
should fix #199

### CODE REVIEW

File: scripts/deploy.sh [hunk 1]
```diff
@@ -17,5 +17,8 @@ if [[ $TRAVIS_BRANCH == "master" ]]; then
 	mkdir pages
 	cp -R dist/docs/documentation/ pages/documentation
 	cp -R dist/docs/storybook/* pages
+	version=$(node -e 'const package = require("./package.json"); console.log(package.version);')
```
Comment (zvonimirfras) [inline scripts/deploy.sh]: Isn't `package.json` version kinda stuck at 0.1.0?

Comment (cal-smith) [reply scripts/deploy.sh]: nope, since this runs after semantic release `package.json` will have the correct value.

File: scripts/deploy.sh [hunk 2]
```diff
@@ -17,5 +17,8 @@ if [[ $TRAVIS_BRANCH == "master" ]]; then
...
+	cp -R dist/docs/documentation/ pages/$version/documentation
+	cp -R dist/docs/storybook/* pages/$version
```
Comment (zvonimirfras) [inline scripts/deploy.sh]: I like these paths :D
