### PR TITLE
fix(search): focus input, and remove it when not in use

### LINKED ISSUE #464: ibm-table-toolbar-search  is allowing  to type without expansion of search-text box.
**Detailed description**

In Carbon’s ToolBar search with experimental theme instead of clicking on search magnifier icon when user clicks on search-text box then it is allowing to write (this typed text will display if user opens the searchBar) and after hitting enter button, it is showing search result.

 **Additional information**

I have attached screenshot of same
Firefox

### LINKED ISSUE #465: ibm-table-toolbar-search  is not closing when user clicks some other carbon component
**Detailed description**
Using Carbon’s ToolBar search with experimental theme ,but ibm-table-toolbar-search  is not closing when user clicks some other carbon component(Overflowmenu, tooltip, buttons etc) in that page.

**Steps to reproduce the issue**
1. Include ibm-table-toolbar(having Ibm-table-toolbar search),overflowMenu and ibm-butttons in page
2. Open that page in browser.
3. Write something in search text box
4. try to open Overflowmenu which is inside the table-grid 
5. You will observe that search bar does not get closed.

 **Additional information**
Searchbar not closing

### PR DESCRIPTION
**Pull request by cal-smith**
closes #465 
closes #464

### CODE REVIEW

**Comment by magedhennawy** [comment]
Cant see why its failing to deploy.. hmmm any ideas @cal-smith

**Comment by cal-smith** [comment]
🤷‍♂️ it's something with netlify, not a big deal since it doesn't stop us deploying

File: src/search/search.component.ts [hunk 1]
```diff
@@ -253,9 +241,9 @@ export class Search implements ControlValueAccessor {
 		this.propagateChange(this.value);
 	}
 
-	openSearch(event) {
+	openSearch() {
 		this.active = true;
-		this.elementRef.nativeElement.querySelector(".bx--search-input").focus();
+		setTimeout(() => this.inputRef.nativeElement.focus());
```
Comment (zvonimirfras) [inline src/search/search.component.ts]: That's so much cleaner 🙌
