### PR TITLE
fix(tab): add correct id to tab content wrapper element

### LINKED ISSUE #3123: Passing custom id to tab component, causing accessibility on aria-controls
When we pass id for cds-tab component, it cause accessibility issue.

Code changes to reproduce issue.
Image

Accessibility report
Image

### PR DESCRIPTION
**Pull request by kush-savani**
Closes carbon-design-system/carbon-components-angular#3123

We are using `aria-controls` on tab-header button but provided id is not present on tab-content. it cause accessibility issue.
  
Before:
Screenshot 2025-03-26 at 10 54 04 AM

After:
Screenshot 2025-03-26 at 10 54 14 AM

#### Changelog

**New**

* {{new thing}}

**Changed**

* {{change thing}}

**Removed**

* {{removed thing}}

### CODE REVIEW

**Review by Akshat55 — DISMISSED** [review]

File: src/tabs/tab.component.ts [hunk 1]
```diff
@@ -60,6 +60,7 @@ import {
 			role="tabpanel"
 			*ngIf="shouldRender()"
 			class="cds--tab-content"
+			[id]='id'
```
Comment (Akshat55) [inline src/tabs/tab.component.ts:63]:
```suggestion
			[id]='"id"
```

File: src/tabs/tab.component.ts [hunk 2]
```diff
@@ -60,6 +60,7 @@ import {
 			role="tabpanel"
 			*ngIf="shouldRender()"
 			class="cds--tab-content"
+			[id]='"id"
```
Comment (Akshat55) [inline src/tabs/tab.component.ts:63]:
```suggestion
			[id]="id"
```

**Review by Akshat55 — APPROVED** [review]
