### PR TITLE
fix(Dropdown) Fix error when the list of items is empty

### LINKED ISSUE #771: Dropdown throws an error when the list of items is empty
## Detailed description

> Component: Dropdown

> When the item list is empty and we try to open the dropdown, we have this error in the console: `ERROR TypeError: Cannot read property 'nativeElement' of undefined`. The component is trying to focus on the first element of the list even when it is empty.

>According to the stacktrace, it fails on dropdown-list.component.ts:348 and it seems to be caused by the call to the function `initFocus()`, when the item list is empty, it set `index = 0`  and then it invokes to `getCurrentElement()` where `listElementList.toArray()[0]` is undefined, so asking for `.nativeElement` throws the error.

## Additional information

* Screenshots

image

image

### PR DESCRIPTION
**Pull request by Donisius**
Closes #771

### CODE REVIEW

File: src/dropdown/list/dropdown-list.component.ts [hunk 1]
```diff
@@ -404,7 +404,7 @@ export class DropdownList implements AbstractDropdownView, AfterViewInit, OnDest
 		if (this.index < 0) {
 			this.index = 0;
 		}
-		this.getCurrentElement().focus();
+		this.getCurrentElement().focus();
```
Comment (cal-smith) [inline src/dropdown/list/dropdown-list.component.ts]: Looks like a trailing space crept in here ... 
```suggestion
		this.getCurrentElement().focus();
```
