### PR TITLE
fix(datepicker): valueChange emits on change

### LINKED ISSUE #643: Changing date picker through keyboard does not work anymore
#600 did not fix it.

DatePickerInput emits a valueChange event and nothing in DatePicker is listening to this ... this is still the case.

### PR DESCRIPTION
**Pull request by cal-smith**
The primary fix here is switching control of value propagation away from
flatpickr and instead handling it ourselves. This has an additional
benefit of simplifying value handling for ngModel, reactive forms,
double binding, etc.

closes #643

### CODE REVIEW

File: src/datepicker/datepicker.component.ts [hunk 1]
```diff
@@ -177,16 +177,19 @@ export class DatePicker implements OnDestroy, AfterViewInit, OnChanges {
...
 			this.flatpickrInstance = flatpickr(`#${this.id}`, this.flatpickrOptions);
-			this.flatpickrInstance.setDate(dates);
 			this.setDateValues(dates);
 		}
 	}
 
 	ngAfterViewInit() {
 		this.flatpickrInstance = flatpickr(`#${this.id}`, this.flatpickrOptions);
+		if (this.value === null) {
+			this.value = [];
```
Comment (youda97) [inline src/datepicker/datepicker.component.ts]: Isn't it already set to this when it is initialized?

File: src/datepicker/datepicker.component.ts [hunk 2]
```diff
@@ -196,12 +199,68 @@ export class DatePicker implements OnDestroy, AfterViewInit, OnChanges {
...
-	doSelect(selectedValue) {
-		this.valueChange.emit(selectedValue);
-		this.propagateChange(selectedValue);
+	/**
+	 * Writes a value from the model to the component. Expects the value to be `null` or `(Date | string)[]`
+	 * @param value value recived from the model
+	 */
+	writeValue(value: (Date | string)[]) {
+		if (!value) {
+			value = [];
```
Comment (youda97) [inline src/datepicker/datepicker.component.ts]: Couldn't this be set in the parameters?

File: src/datepicker/datepicker.component.ts (hunk 1 above)
Comment (cal-smith) [reply src/datepicker/datepicker.component.ts]: It is initialized to `[]`, however `ngModel` and friends can override that with an explicit `null`, so in this case we just reset it (since nothing else in the component is set up to handle `null`s)

**However** you bring up a good point ... I'll change this (and the other comment) out to use a setter/getter on the input instead so we can easilly catch any instance of `null` value passing
