### PR TITLE
fix(date picker): Show DatePicker when calendar icon is clicked

### LINKED ISSUE #837: DatePicker Range component - DatePicker should also show when we click on the calendar icon inside the field
DatePicker is only showing when we click on the text Field. It should also show when we click on the calendar icon inside the field, On hover its showing pointer icon but on click nothing is happening.

### PR DESCRIPTION
**Pull request by Donisius**
Closes #837 

DatePicker could not be opened when the calendar icon is clicked. A toggle has been added to open and close the DatePicker when the calendar icon is clicked.

#### Changelog

**New**

* It is now possible to open and close the calendar when the calendar icon is clicked.

### CODE REVIEW

File: src/datepicker-input/datepicker-input.component.ts [hunk 1]
```diff
@@ -78,7 +78,7 @@ export class DatePickerInput {
 
 	@Output() valueChange: EventEmitter<string> = new EventEmitter();
 
-	@Output() toggleCalendar: EventEmitter<boolean> = new EventEmitter();
+	@Output() selected = new EventEmitter();
```
Comment (cal-smith) [inline src/datepicker-input/datepicker-input.component.ts]: Not sure that the semantics of `selected` as used elsewhere in the codebase make sense here as well ... there's no value emitted for one thing

Comment (Donisius) [reply src/datepicker-input/datepicker-input.component.ts]: Would something like openCalendar be better?

Comment (cal-smith) [reply src/datepicker-input/datepicker-input.component.ts]: You may even just be able to forward the `click` event - that way all the cases are covered

Comment (cal-smith) [reply src/datepicker-input/datepicker-input.component.ts]: Otherwise `open` or `openCalendar` would probably make more sense ... but you'd want to make sure they fire for all cases of clicking on the input

Comment (Donisius) [reply src/datepicker-input/datepicker-input.component.ts]: Okay, that makes sense

**Comment by cal-smith** [comment]
fyi @Donisius we'll need to add these changes for v2 as well 👍

**Comment by Donisius** [comment]
@cal-smith it already works as expected on v2

**Comment by cal-smith** [comment]
Oh awesome!
