### PR TITLE
fix(content-switcher): DAP Issues

### LINKED ISSUE #111: Fix DAP issues for Content Switcher
Level | Description
-- | --
V | All content must reside within a WAI-ARIA landmark or labelled region role. | Details
V | Widget with role of tablist must have no more than one tabbable element.

### PR DESCRIPTION
**Pull request by youda97**
Closes #111

### CODE REVIEW

File: src/content-switcher/content-switcher.component.ts [hunk 1]
```diff
@@ -31,7 +34,10 @@ export class ContentSwitcher implements AfterViewInit {
 
 	@ContentChildren(ContentSwitcherOption) options: QueryList<ContentSwitcherOption>;
 
+	constructor(private elementRef: ElementRef) {}
```
Comment (zvonimirfras) [inline src/content-switcher/content-switcher.component.ts]: Use `protected` so components are extendible.
```suggestion
	constructor(protected elementRef: ElementRef) {}
```
